import Head from "next/head";
import React, { useEffect, useState } from "react";
import Banner1 from "../components/banner/Banner1";
import Preloader from "../components/common/Preloader ";
import Footer from "../components/footer/Footer";
import CreativeService from "../components/service/CreativeService";
import Testimonial1 from "../components/testimonial/Testimonial1";
import WhyChooseUs from "../components/whyChooseUs/WhyChooseUs";
import Header1 from "./../components/header/Header1";

export default function Home() {
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    setLoading(false);
    setTimeout(() => {
      setLoading(true);
    }, 1500);
  }, []);

  return (
    <>
      {!loading ? (
        <Preloader />
      ) : (
        <>
          <Head>
            <title>WorkDeal</title>
            <meta charSet="UTF-8" />
            <meta httpEquiv="X-UA-Compatible" content="IE=edge"></meta>
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1.0"
            ></meta>
            <meta name="description" content="Generated by create next app" />
            <link
              rel="icon"
              href="assets/images/fevicon.png"
              type="image/gif"
              sizes="20x20"
            />
          </Head>
          <Header1 />
          <Banner1 />
          <CreativeService />
          <WhyChooseUs />
          <Testimonial1 />
          <Footer />
        </>
      )}
    </>
  );
}
